project:
  type: website
  output-dir: docs
  
website:
  title: "tis_web"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/chadyuu/tis-web/
    contents:
      - index.qmd
      - text_retrieval.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

